force-app/main/default/objects/PushTopicCustom__c/PushTopicCustom__c.object-meta.xml
<CustomObject>
    <label>Push Topic Custom</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Push Topic Custom Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Push Topic Custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PushTopicCustom__c/fields/ButtonNumber__c.field-meta.xml
<CustomField>
    <fullName>ButtonNumber__c</fullName>
    <label>Button Number</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>one</fullName>
            </value>
            <value>
                <fullName>two</fullName>
            </value>
            <value>
                <fullName>three</fullName>
            </value>
            <value>
                <fullName>four</fullName>
            </value>
            <value>
                <fullName>five</fullName>
            </value>
            <value>
                <fullName>six</fullName>
            </value>
            <value>
                <fullName>seven</fullName>
            </value>
            <value>
                <fullName>eight</fullName>
            </value>
            <value>
                <fullName>nine</fullName>
            </value>
            <value>
                <fullName>zero</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PushTopicCustom__c/fields/Finished__c.field-meta.xml
<CustomField>
    <fullName>Finished__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Finished</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PushTopicCustom__c/fields/Tied__c.field-meta.xml
<CustomField>
    <fullName>Tied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TicTacToeSettings__c/TicTacToeSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TicTacToe Settings</label>
</CustomObject>

force-app/main/default/objects/TicTacToeSettings__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <label>ClientId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TicTacToeSettings__c/fields/Destination_Org_pushTopic_RecordId__c.field-meta.xml
<CustomField>
    <fullName>Destination_Org_pushTopic_RecordId__c</fullName>
    <label>Destination Org pushTopic RecordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TicTacToeSettings__c/fields/Instance_URL__c.field-meta.xml
<CustomField>
    <fullName>Instance_URL__c</fullName>
    <label>Instance URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TicTacToeSettings__c/fields/pushTopic_RecordId__c.field-meta.xml
<CustomField>
    <fullName>pushTopic_RecordId__c</fullName>
    <label>pushTopic RecordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TicTacToeSettings__c/fields/sId__c.field-meta.xml
<CustomField>
    <fullName>sId__c</fullName>
    <label>sId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TicTacToeController.cls
/**
 * @description       : Controller class for TicTacToe LWC
 * @author            : Ayush Sharma
 * @last modified on  : 06-30-2021
 * @last modified by  : Ayush Sharma
 * Modifications Log 
 * Ver   Date         Author         Modification
 * 1.0   06-30-2021   Ayush Sharma   Initial Version
**/
public with sharing class TicTacToeController {
    
    /**
    * @description Method runs on Button click and Sends information to another Org.
    * @author Ayush Sharma | 06-30-2021 
    * @param String coordinate 
    * @param Boolean finished 
    * @param Boolean tied 
    **/
    @AuraEnabled
    public static void chancePlayed( String coordinate, Boolean finished, Boolean tied ){

        TicTacToeSettings__c tSetting = TicTacToeSettings__c.getInstance('main');
        String authorizationHeader = 'Bearer '+tSetting.sId__c;
        HttpRequest httpRequest = new HttpRequest();
        httpRequest.setMethod('PATCH');
        httpRequest.setEndpoint( tSetting.instance_Url__c+'/services/data/v52.0/sobjects/PushTopicCustom__c/'+tSetting.Destination_Org_pushTopic_RecordId__c );
        httpRequest.setHeader('Authorization', authorizationHeader);
        httpRequest.setHeader('Content-Type', 'application/json;charset=UTF-8');
        if( finished ){
            httpRequest.setBody('{ "ButtonNumber__c" : "'+coordinate+'", "Finished__c" : true }');
        }
        else if( tied ){
            httpRequest.setBody('{ "ButtonNumber__c" : "'+coordinate+'", "Tied__c" : true }');
        }
        else{
            httpRequest.setBody('{ "ButtonNumber__c" : "'+coordinate+'"}');
        }
        Http http = new Http();
        HTTPResponse httpResponse = http.send(httpRequest);
        system.debug('httpResponse -> '+ httpResponse.getBody());
        system.debug('httpResponse.getHeaderKeys() -> '+ httpResponse.getHeaderKeys());

    }

    /**
    * @description Method Authorizes the Org and get the Session Id.
    * @author Ayush Sharma | 06-30-2021 
    **/
    @AuraEnabled
    public static void getAuthorization(){

        TicTacToeSettings__c tSetting = TicTacToeSettings__c.getInstance('main');
        HttpRequest httpRequest = new HttpRequest();
        httpRequest.setMethod('POST');
        httpRequest.setEndpoint( 'https://login.salesforce.com/services/oauth2/token' );
        String reqBody ='grant_type=password&client_id='+tSetting.ClientId__c
                        +'&client_secret='+tSetting.Client_Secret__c
                        +'&username='+tSetting.Username__c+'&password='+tSetting.Password__c;
        httpRequest.setBody(reqBody);
        httpRequest.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        Http http = new Http();
        HTTPResponse res = http.send(httpRequest);
        Map<String, Object> mapResponse = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
        tSetting.sId__c = (String)mapResponse.get( 'access_token' );
        update tSetting;
    }

    /**
    * @description Method Resets the PushTopic record on Initialization.
    * @author Ayush Sharma | 06-30-2021 
    **/
    @AuraEnabled
    public static void resetPushTopicRecord(){
        TicTacToeSettings__c tSetting = TicTacToeSettings__c.getInstance('main');
        PushTopicCustom__c pt = new PushTopicCustom__c( Id = tSetting.pushTopic_RecordId__c );
        pt.ButtonNumber__c = null;
        pt.Finished__c = false;
        pt.Tied__c = false;
        update pt;
    }

}